.TH shim 1 "February 14th, 2013" "Paradigm4 Inc."
.SH NAME
shim \- A basic HTTP service for SciDB.
.SH SYNOPSIS
.B shim
[\-h] [\-f] [\-n \fIPAM_service_name\fR] [\-p \fIhttpport\fR] [\-r \fIdocumentroot\fR] [\-s \fIscidbport\fR]
.SH DESCRIPTION
Shim is a super-basic SciDB client that exposes SciDB queries
through a simple HTTP API.
.TP
Shim must run on the system that a SciDB coordinator runs on.
.TP
Start shim and navigate to http://localhost:8080/api.html for detailed help on the API.

.SH OPTIONS
.TP
.B \-h
Display help
.TP
.B \-f
Run in the foreground (defaults to the background).
.TP
.B \-n \fIPAM_service_name\fR
Specify the PAM service name to use for authentication. The default is "login." See available services listed in /etc/pam.d/.
.TP
.B \-p \fIport\fR
Listen on the specified port. Shim defaults to ports 8080 and 8083(SSL).
.TP
.B \-r \fIpath\fR
Set the HTTP document root to the specified path. Default installations
of shim use /var/lib/shim/wwwroot by default.
.TP
.B \-s \fIport\fR
Talk to SciDB on the specified port, 1239 by default.


.SH AUTHOR
Written by Bryan Wayne Lewis, Paradigm4 Inc.
.SH COPYRIGHT
Copyright (C) 2012 Paradigm4 Inc.
