#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          shimsvc
# Required-Start:    $syslog $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: shim
# Description:       A simple SciDB web service.
### END INIT INFO

# Locate scidb heuristics
SCIDB_DIR=$(dirname $(dirname $(which scidb) 2>/dev/null) 2>/dev/null)
if test -z "${SCIDB_DIR}"; then
  if test -d /opt/scidb; then
    SCIDB_DIR=$(dirname $(dirname $(find /opt/scidb/ -name shim 2>/dev/null | tail -n 1) 2>/dev/null) 2>/dev/null)
#    SCIDB_DIR=$(ls -t /opt/scidb | head -n 1)
#    if test -n "${SCIDB_DIR}"; then SCIDB_DIR="/opt/scidb/${SCIDB_DIR}";fi
  fi
  if test -z "${SCIDB_DIR}"; then
    echo "Error, can't find SciDB, is it in the PATH?" 2>&1
    exit 1
  fi
fi

export LD_LIBRARY_PATH="${SCIDB_DIR}/lib"
export SHIM="${SCIDB_DIR}/bin/shim"

case $1 in
        start)
            echo "Starting shim"
            "${SHIM}"
            ;;
        restart)
            echo "Stopping shim"
            P=$(cat /var/run/shim.pid 2>/dev/null)
            if test -z "${P}"; then
              killall shim
            else
              kill $P 2>/dev/null || echo "Couldn't kill process $P (privilege error?)"
            fi
            echo "Starting shim"
            "${SHIM}"
            ;;
        status)
            P=$(cat /var/run/shim.pid 2>/dev/null)
            Q=$(ps aux | grep shim | grep $P 2>/dev/null)
            if test -z "${Q}"; then Q="not found";fi
            echo "Shim process ${Q}"
            ;;
        stop)
            echo "Stopping shim"
            P=$(cat /var/run/shim.pid 2>/dev/null)
            if test -z "${P}"; then
              killall shim 2>/dev/null || echo >/dev/null
            else
              kill $P 2>/dev/null || echo "Couldn't kill process $P (privilege error?)"
            fi
            ;;
esac
